# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\"!\n\x10UserVerification\x12\r\n\x05\x65mail\x18\x01 \x01(\t\"\x1c\n\x08Response\x12\x10\n\x08validate\x18\x01 \x01(\x08\x32\x43\n\x12UserManagerService\x12-\n\rValidateEmail\x12\x11.UserVerification\x1a\t.Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERVERIFICATION']._serialized_start=17
  _globals['_USERVERIFICATION']._serialized_end=50
  _globals['_RESPONSE']._serialized_start=52
  _globals['_RESPONSE']._serialized_end=80
  _globals['_USERMANAGERSERVICE']._serialized_start=82
  _globals['_USERMANAGERSERVICE']._serialized_end=149
# @@protoc_insertion_point(module_scope)
